/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#0f131c',
        'surface-dim': '#0f131c',
        'surface-bright': '#353943',
        'surface-container-lowest': '#0a0e17',
        'surface-container-low': '#181b25',
        'surface-container': '#1c1f29',
        'surface-container-high': '#262a34',
        'surface-container-highest': '#31353f',
        'on-surface': '#dfe2ef',
        'on-surface-variant': '#bbcabf',
        'inverse-surface': '#dfe2ef',
        'inverse-on-surface': '#2c303a',
        outline: '#86948a',
        'outline-variant': '#3c4a42',
        'surface-tint': '#4edea3',
        primary: '#4edea3',
        'on-primary': '#003824',
        'primary-container': '#10b981',
        'on-primary-container': '#00422b',
        'inverse-primary': '#006c49',
        secondary: '#d0bcff',
        'on-secondary': '#3c0091',
        'secondary-container': '#571bc1',
        'on-secondary-container': '#c4abff',
        tertiary: '#89ceff',
        'on-tertiary': '#00344d',
        'tertiary-container': '#23acf1',
        'on-tertiary-container': '#003d59',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        background: '#090d16',
        'on-background': '#dfe2ef',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        jetbrains: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        'sm': '0.125rem',
        DEFAULT: '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'gutter': '1rem',
        'gutter-lg': '1.5rem',
        'margin': '1rem',
        'margin-md': '1.5rem',
        'margin-lg': '2rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
      }
    },
  },
  plugins: [],
}
